env:
- LIBRARY_SOURCE_DIRECTORY=/tmp/fdk-aac LIBRARY_INSTALL_DIRECTORY=/opt/fdk-aac

language: java

services:
- docker

before_install:
- git checkout ${TRAVIS_BRANCH} # This deals with detached head issue for proper coveralls.io integration
- docker build --cache-from azul/zulu-openjdk:11 --build-arg LIBRARY_INSTALL_DIRECTORY=${LIBRARY_INSTALL_DIRECTORY} --build-arg LIBRARY_SOURCE_DIRECTORY=${LIBRARY_SOURCE_DIRECTORY} -t jna-aac-encoder .

jdk:
- openjdk11

script:
- if [ ${TRAVIS_BRANCH} != 'master' ]; then docker run -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" jna-aac-encoder clean junitPlatformTest -PlibPath=${LIBRARY_INSTALL_DIRECTORY}/lib ; fi
- if [ ${TRAVIS_BRANCH} == 'master' ]; then docker run -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" jna-aac-encoder clean junitPlatformTest jacocoTestReport coveralls -PlibPath=${LIBRARY_INSTALL_DIRECTORY}/lib ; fi
