language: java

services:
  - docker

before_install:
  - docker build --cache-from openjdk:9-jdk-slim-sid -t jna-aac-encoder .

install:
  - git checkout ${TRAVIS_BRANCH}

jdk:
  - oraclejdk9

cache:
  directories:
  - $HOME/.m2

script:
  - docker run -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" jna-aac-encoder clean junitPlatformTest jacocoTestReport coveralls

