language: java

services:
  - docker

before_install:
  - docker build -t jna-aac-encoder .

jdk:
  - oraclejdk9

script:
  - docker run jna-aac-encoder clean junitPlatformTest jacocoTestReport coveralls