language: java

services:
  - docker

before_install:
  - docker build -t jna-aac-encoder .

jdk:
  - oraclejdk9

after_success:
  - docker run -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" jna-aac-encoder clean junitPlatformTest jacocoTestReport coveralls