language: java

services:
  - docker

before_install:
  - git checkout ${TRAVIS_BRANCH} # This deals with detached head issue for proper coveralls.io integration
  - docker build --cache-from openjdk:9-jdk-slim-sid -t jna-aac-encoder .

jdk:
  - oraclejdk9

script:
  - docker run -e "COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}" jna-aac-encoder '-PlibPath=${LIBRARY_BUILD_DIRECTORY}/lib' clean junitPlatformTest jacocoTestReport coveralls

